### ISSUE TITLE
docker build -t $YOUR_USERNAME/iphone-vpn

### ISSUE THREAD

**Issue by frankmeten** [Allezxandre/iPhone-VPN#1]
When I run it , system said:
[ docker build -t /home/ec2-user/iPhone-VPN
docker: "build" requires 1 argument.
See 'docker build --help'.

Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH
]

**Comment by allezxandre** [comment]
Did you fix it yet? The command is `docker build -t frankmeten/iPhone-VPN /home/ec2-user/iPhone-VPN`

**Comment by frankmeten** [comment]
Yes, I fix it.
[ docker build --help

Usage: docker build [OPTIONS] PATH | URL | -

Build a new image from the source code at PATH

  -c, --cpu-shares=0    CPU shares (relative weight)
  --cgroup-parent=      Optional parent cgroup for the container
  --cpu-period=0        Limit the CPU CFS (Completely Fair Scheduler) period
  --cpu-quota=0         Limit the CPU CFS (Completely Fair Scheduler) quota
  --cpuset-cpus=        CPUs in which to allow execution (0-3, 0,1)
  --cpuset-mems=        MEMs in which to allow execution (0-3, 0,1)
  -f, --file=           Name of the Dockerfile (Default is 'PATH/Dockerfile')
  --force-rm=false      Always remove intermediate containers
  --help=false          Print usage
  -m, --memory=         Memory limit
  --memory-swap=        Total memory (memory + swap), '-1' to disable swap
  --no-cache=false      Do not use cache when building the image
  --pull=false          Always attempt to pull a newer version of the image
  -q, --quiet=false     Suppress the verbose output generated by the containers
  --rm=true             Remove intermediate containers after a successful build
  -t, --tag=            Repository name (and optionally a tag) for the image
]
I use "docker build -t justatag /home/ec2-user/iPhone-VPN"
